Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/spartans/Documents/csc102-defuse/bomb/code/Duck_GUI_V2.py", line 68, in <lambda>
    self.canvas.bind_all("<Up>",    lambda e: self.move( 0, -1))
                                              ^^^^^^^^^^^^^^^^^
  File "/home/spartans/Documents/csc102-defuse/bomb/code/Duck_GUI_V2.py", line 491, in move
    self.allow_interaction_for_phase()
  File "/home/spartans/Documents/csc102-defuse/bomb/code/Duck_GUI_V2.py", line 510, in allow_interaction_for_phase
    self.wires_frame.hide()
  File "/home/spartans/Documents/csc102-defuse/bomb/code/Duck_GUI_V2.py", line 420, in hide
    self.timer_bar.pack_forget()
    ^^^^^^^^^^^^^^
AttributeError: 'WiresRevealFrame' object has no attribute 'timer_bar'
