spartans@raspberrypi:~/Documents/csc102-defuse $ /bin/python /home/spartans/Documents/csc102-defuse/bomb/code/bomb.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Running On Raspberry Pi
7-Segment Pins
Keypad Pins
Jumper Wires Pins
Button RGB Pins
Toggle Switches Pins
Serial Number: A00CE7I
Toggles Target: 0111/7
Wires Target: 10101/21
Keypad Target: 25663/ALOOF/MIGHTY/BXVWIN (Rot=15)
Button Target: 7 (B)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/spartans/Documents/csc102-defuse/bomb/code/bomb.py", line 281, in start_game
    setup_phases()
  File "/home/spartans/Documents/csc102-defuse/bomb/code/bomb.py", line 70, in setup_phases
    gamble = Gamble(
             ^^^^^^^
  File "/home/spartans/Documents/csc102-defuse/bomb/code/bomb_phases.py", line 546, in __init__
    self.roll_button = Button(
                       ^^^^^^^
TypeError: Button.__init__() got an unexpected keyword argument 'text'
Interacting with toggles
Interacting with wires
Interacting with toggles
Interacting with keypad
Interacting with gamble
^CTraceback (most recent call last):
  File "/home/spartans/Documents/csc102-defuse/bomb/code/bomb.py", line 342, in <module>
    window.mainloop()
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1943, in __call__
    def __call__(self, *args):
